### PR TITLE
kie-issues#500: Replace copyright headers/comments on kie-benchmarks as part of the migration to Apache #500 #520

### PR DESCRIPTION
**Pull request by ederign**
More info at: https://github.com/kiegroup/kie-issues/issues/413

### CODE REVIEW

**Comment by ederign** [comment]
@lucamolteni, when you have a chance, could you please review this? Its part of Apache migration

**Review by kbowers-ibm — APPROVED** [review]
LGTM! (Once merge conflicts resolved)

**Review by LightGuard — APPROVED** [review]

**Comment by LightGuard** [comment]
Conflicting commit: https://github.com/apache/incubator-kie-benchmarks/commit/24479c48c7d2d8a2e5fd6a4f6c630fb296f34dbc

The SimpleDummyFactsMatchRatioExpertBenchmark.java file was deleted. It should be a very simple conflict cleanup :)

**Review by mariofusco — APPROVED** [review]

**Comment by yesamer** [comment]
@ederign We just need to merge this PR to close the whole Headers refactoring task :muscle:  :fire:
Can you please resolve the above conflict? Thanks! :pray:

**Comment by ederign** [comment]
@yesamer fixed.

**Review by yesamer — APPROVED** [review]
Thanks @ederign

**Comment by yesamer** [comment]
@LightGuard Do you think we can merge it? Is java 11 build failure unrelated?

**Comment by LightGuard** [comment]
I don't have any issues merging this.

**Comment by LightGuard** [comment]
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project drools-benchmarks-common: Fatal error compiling: error: invalid target release: 17 -> [Help 1]

Makes sense, code targeted for 17 can't compile on a version 11 JDK :)

**Pull request merged**
