### PR TITLE
[DROOLS-7581] Fix kie-benchmarks GHA : Could not find artifact org.dr…

### PR DESCRIPTION
**Pull request by tkobayas**
…ools:drools-reliability-h2mvstore:jar:8.45.0-SNAPSHOT

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by hellowdan** [comment]
@skulisek please take a look

**Review by hellowdan — APPROVED** [review]

**Comment by skulisek** [comment]
LGTM, I wasn't sure if adding repositories was an option or just a workaround so I didn't suggest it.

**Comment by tkobayas** [comment]
Hi @baldimir ! I think we need to involve you here.

This PR (Adding repository.jboss.org) is opposite to our apache migration direction.

With [kie-issues#628](https://github.com/apache/incubator-kie-issues/issues/628), we are going to release snapshot Maven artifacts to Apache Nexus instead of JBoss Nexus.

Indeed, the referenced repository in kie-benchmarks was changed from jboss to apache with this PR.
https://github.com/apache/incubator-kie-benchmarks/pull/267

However, the snapshot release to apache is not yet done, so kie-benchmarks fails to build at the moment.

https://issues.apache.org/jira/browse/INFRA-25077
 -> According to the comments, it's really in progress and it may complete in a few days.

https://repository.apache.org/content/groups/public/
 -> https://repository.apache.org/content/groups/public/org/drools returns 404 at the moment.

Interestingly, kie-benchmarks failed since it introduced a new dependency `org.drools:drools-reliability-h2mvstore:jar:8.45.0-SNAPSHOT`. Other SNAPSHOT dependencies worked thanks to GHA action "cache" `actions/cache@v2` configured in pull_request.yml.

@baldimir  ,  is it okay to merge this PR (Adding repository.jboss.org) until actually snapshot artifacts will be released in apache repo? (once released in apache repo, I will remove the jboss repo reference)

**Comment by baldimir** [comment]
I personally don't agree with merging this as we will be releasing snapshost to Apache Nexus soon. If the build fails somewhere, I would suggest to please use a custom settings.xml file. Sorry for this, we are working to get the snapshots released as soon as possible.

**Comment by tkobayas** [comment]
@baldimir Thank you for the reply. It's okay for me to close this PR. We can run benchmarks locally.

**Pull request closed without merging**
